import { useState } from "react";
import { ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { trpc } from "../lib/trpc";
import NotFound from "../pages/NotFound";
import CreatePostPanel from "./CreatePostPanel";
import { BrandMark, ThemeToggle } from "../components/Brand";

export function AdminLogin() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const login = trpc.admin.login.useMutation({ onSuccess: () => location.assign("/admin"), onError: () => location.assign("/404") }); return <main className="auth-page"><header className="auth-header"><BrandMark /><ThemeToggle /></header><div className="auth-layout"><aside className="auth-story"><p className="eyebrow"><span className="eyebrow-line" /> Private newsroom</p><h2>Make the<br /><em>signal</em> matter.</h2><p className="auth-story-copy">A focused editorial desk for shaping the next considered brief.</p></aside><section className="auth-panel"><div className="auth-panel-inner"><p className="eyebrow">Newsroom</p><h1>Editorial access</h1><p className="auth-intro">Sign in to shape the next edition of Aurikrex Bytes.</p><form className="auth-form" onSubmit={(e) => { e.preventDefault(); login.mutate({ email, password, remember: true }); }}><label>Email address<input type="email" onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" onChange={(e) => setPassword(e.target.value)} required /></label><label className="check"><input type="checkbox" defaultChecked /> Remember this device</label><button className="primary-button full-width" type="submit">Continue <ArrowUpRight size={16} /></button></form></div></section></div></main>; }

export function AdminDashboard() { const session = trpc.admin.session.useQuery(); const posts = trpc.admin.posts.useQuery(undefined, { enabled: Boolean(session.data) }); if (!session.data) return <NotFound />; return <main className="admin-shell"><aside className="admin-rail"><BrandMark compact /><div className="rail-label">Newsroom</div><p className="rail-role">{session.data.role}</p><Link className="rail-link" href="/">View public brief <ArrowUpRight size={15} /></Link><ThemeToggle /></aside><section className="admin-content"><div className="admin-topline"><div><p className="eyebrow">Editorial desk</p><h1>Publishing queue</h1></div><span className="status-pill">Live workspace</span></div><div className="metric-row"><div><span>Total posts</span><strong>{posts.data?.length || 0}</strong></div><div><span>Publishing states</span><strong>4</strong></div><div><span>Next scheduled</span><strong>—</strong></div></div><CreatePostPanel /><div className="table-card"><div className="table-heading"><h2>Recent posts</h2><span>Latest activity</span></div>{posts.data?.map((post) => <div className="table-row" key={post.id}><span>{post.headline}</span><span className="status">{post.status}</span></div>)}</div></section></main>; }
