import { useState } from "react";
import { Link } from "wouter";
import { trpc } from "../lib/trpc";
import NotFound from "../pages/NotFound";

function AdminFrame({ children, title, active }: { children: React.ReactNode; title: string; active: "team" | "analytics" }) {
  const session = trpc.admin.session.useQuery();
  if (session.isLoading) return <main className="auth-wrap"><p className="muted">Loading newsroom…</p></main>;
  if (!session.data || session.data.role !== "admin") return <NotFound />;
  return <main className="admin-shell"><aside><p className="eyebrow">Aurikrex Bytes</p><h2>Newsroom</h2><p className="muted admin-role">{session.data.role}</p><nav className="admin-nav"><Link className={active === "team" ? "active" : ""} href="/admin/team">Team</Link><Link className={active === "analytics" ? "active" : ""} href="/admin/analytics">Analytics</Link><Link href="/admin">Inbox</Link></nav></aside><section className="admin-content management-page"><p className="eyebrow">Administration</p><h1>{title}</h1>{children}</section></main>;
}

export function TeamManagement() {
  const session = trpc.admin.session.useQuery(); const utils = trpc.useUtils(); const members = trpc.admin.users.list.useQuery(undefined, { enabled: session.data?.role === "admin" }); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<"admin" | "editor">("editor"); const [message, setMessage] = useState("");
  const create = trpc.admin.users.create.useMutation({ onSuccess: () => { setEmail(""); setPassword(""); setMessage("Team member created."); void utils.admin.users.list.invalidate(); }, onError: error => setMessage(error.message) });
  const changeRole = trpc.admin.users.changeRole.useMutation({ onSuccess: () => void utils.admin.users.list.invalidate(), onError: error => setMessage(error.message) }); const revoke = trpc.admin.users.revoke.useMutation({ onSuccess: () => { setMessage("Access revoked. Existing sessions are invalid immediately."); void utils.admin.users.list.invalidate(); }, onError: error => setMessage(error.message) });
  return <AdminFrame title="Team" active="team"><div className="management-grid"><section className="table-card"><h2>Add team member</h2><form className="team-form" onSubmit={event => { event.preventDefault(); create.mutate({ email, password, role }); }}><label className="field-label" htmlFor="team-email">Email<input id="team-email" className="text-input" type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label className="field-label" htmlFor="team-password">Temporary password<input id="team-password" className="text-input" type="password" minLength={8} value={password} onChange={event => setPassword(event.target.value)} required /></label><label className="field-label" htmlFor="team-role">Role<select id="team-role" className="text-input" value={role} onChange={event => setRole(event.target.value as "admin" | "editor")}><option value="editor">Editor</option><option value="admin">Admin</option></select></label><button className="button" type="submit" disabled={create.isPending}>Create account</button></form>{message && <p className="form-message">{message}</p>}</section><section className="table-card team-list-card"><h2>Accounts</h2>{members.isLoading ? <p className="muted">Loading accounts…</p> : <div className="team-list">{members.data?.map(member => <div className="team-row" key={member.id}><div><strong>{member.email}</strong><p className="muted">Created {new Date(member.createdAt).toLocaleDateString()}</p></div><div className="team-row-actions"><span className={`account-status ${member.isActive ? "active" : "revoked"}`}>{member.isActive ? "Active" : "Revoked"}</span><select aria-label={`Change role for ${member.email}`} value={member.role} disabled={!member.isActive || changeRole.isPending} onChange={event => changeRole.mutate({ id: member.id, role: event.target.value as "admin" | "editor" })}><option value="editor">Editor</option><option value="admin">Admin</option></select><button className="text-button danger" disabled={!member.isActive || revoke.isPending} onClick={() => { if (window.confirm(`Revoke access for ${member.email}?`)) revoke.mutate({ id: member.id }); }}>Revoke</button></div></div>)}</div>}</section></div></AdminFrame>;
}

export function AnalyticsDashboard() {
  const session = trpc.admin.session.useQuery(); const analytics = trpc.admin.analytics.useQuery(undefined, { enabled: session.data?.role === "admin" }); const maxViews = Math.max(1, ...(analytics.data?.viewsByHour.map(item => item.views) || [1]));
  return <AdminFrame title="Analytics" active="analytics"><div className="analytics-metrics"><div className="metric-card"><strong>{analytics.data?.totalViews ?? "—"}</strong><span>Total post views</span></div><div className="metric-card"><strong>{analytics.data?.totalReaders ?? "—"}</strong><span>Registered readers</span></div><div className="metric-card"><strong>{analytics.data?.mostRead.length ?? "—"}</strong><span>Posts with views</span></div></div><div className="analytics-columns"><section className="table-card"><h2>Most read</h2>{analytics.data?.mostRead.length ? analytics.data.mostRead.map(post => <div className="analytics-row" key={post.id}><span>{post.headline}</span><strong>{post.viewCount}</strong></div>) : <p className="muted">No published post views yet.</p>}</section><section className="table-card"><h2>Top searches</h2>{analytics.data?.topSearches.length ? analytics.data.topSearches.map(item => <div className="analytics-row" key={item.query}><span>“{item.query}”</span><strong>{item.count}</strong></div>) : <p className="muted">No archive searches yet.</p>}</section></div><section className="table-card hour-chart"><h2>Views by hour</h2><p className="muted">All-time view timestamps, with the 8 AM drop highlighted.</p><div className="bars">{analytics.data?.viewsByHour.map(item => <div className={`bar-column ${item.hour === 8 ? "drop-hour" : ""}`} key={item.hour}><div className="bar" style={{ height: `${Math.max(item.views ? 8 : 2, item.views / maxViews * 150)}px` }} title={`${item.views} views at ${item.hour}:00`} /><span>{item.hour}</span></div>)}</div></section></AdminFrame>;
}
