import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { trpc } from "../lib/trpc";
import NotFound from "../pages/NotFound";

const HEADLINE_LIMIT = 120;
const BODY_LIMIT = 800;
type FormErrors = { imageUrl?: string; headline?: string; body?: string; submit?: string };

function AdminFrame({ role, children }: { role: string; children: React.ReactNode }) {
  return <main className="admin-shell"><aside><p className="eyebrow">Aurikrex Bytes</p><h2>Newsroom</h2><p className="muted admin-role">{role}</p><Link href="/admin">Back to inbox</Link></aside><section className="admin-content new-post-page">{children}</section></main>;
}

export function NewPostPage() {
  const session = trpc.admin.session.useQuery();
  const [, editParams] = useRoute("/admin/new/:draftId");
  const editId = editParams?.draftId ? Number(editParams.draftId) : undefined;
  const existing = trpc.admin.post.useQuery({ id: editId || 0 }, { enabled: Boolean(editId) });
  const signature = trpc.admin.cloudinarySignature.useQuery(undefined, { enabled: Boolean(session.data) });
  const createPost = trpc.admin.createPost.useMutation(); const editPost = trpc.admin.editPost.useMutation();
  const [, navigate] = useLocation();
  const [headline, setHeadline] = useState(""); const [body, setBody] = useState(""); const [imageUrl, setImageUrl] = useState("");
  const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState(""); const [errors, setErrors] = useState<FormErrors>({}); const [fileKey, setFileKey] = useState(0); const [hydrated, setHydrated] = useState(false);

  useEffect(() => { if (existing.data && !hydrated) { setHeadline(existing.data.headline); setBody(existing.data.body); setImageUrl(existing.data.imageUrl || ""); setHydrated(true); } }, [existing.data, hydrated]);
  if (session.isLoading || (editId && existing.isLoading)) return <main className="auth-wrap"><p className="muted">Loading newsroom…</p></main>;
  if (!session.data || (editId && !existing.data)) return <NotFound />;
  const currentRole = session.data.role;

  async function upload(file: File) {
    setUploadError(""); setUploading(true);
    try { if (!signature.data?.configured || !("signature" in signature.data)) throw new Error("Cloudinary is not configured yet."); const form = new FormData(); form.append("file", file); form.append("api_key", signature.data.apiKey); form.append("timestamp", String(signature.data.timestamp)); form.append("folder", signature.data.folder); form.append("signature", signature.data.signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${signature.data.cloudName}/image/upload`, { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Upload failed"); setImageUrl(result.secure_url); }
    catch (error) { setUploadError(error instanceof Error ? error.message : "Upload failed"); } finally { setUploading(false); }
  }
  function validate(): FormErrors { const next: FormErrors = {}; if (!imageUrl) next.imageUrl = "Upload an image before continuing."; if (!headline.trim()) next.headline = "Headline is required."; if (!body.trim()) next.body = "Body is required."; return next; }
  async function saveDraft(destination: "preview" | "draft") { const next = validate(); setErrors(next); if (Object.keys(next).length) return; try { let id = editId; if (editId) await editPost.mutateAsync({ id: editId, headline: headline.trim(), body: body.trim(), imageUrl }); else { const result = await createPost.mutateAsync({ headline: headline.trim(), body: body.trim(), imageUrl }); id = result.id; } if (destination === "preview" && id) navigate(`/admin/preview/${id}?role=${currentRole}`); else setErrors({ submit: "Draft saved. You can find it in the Inbox." }); } catch (error) { setErrors({ submit: error instanceof Error ? error.message : "Could not save post." }); } }
  function onFileChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) void upload(file); }
  function onSubmit(event: FormEvent) { event.preventDefault(); void saveDraft("preview"); }
  const busy = uploading || createPost.isPending || editPost.isPending;
  return <AdminFrame role={currentRole}><header className="new-post-heading"><div><p className="eyebrow">Editorial desk</p><h1>{editId ? "Edit Post" : "New Post"}</h1><p className="muted">Create a story draft, then preview it before its next publishing step.</p></div></header><form className="new-post-form" onSubmit={onSubmit} noValidate>
    <section className="table-card image-upload-card"><div className="field-heading"><div><label className="field-label" htmlFor="post-image">Image</label><p className="field-help">Upload the image for this news card.</p></div>{imageUrl && <button type="button" className="text-button danger" onClick={() => { setImageUrl(""); setFileKey(key => key + 1); }}>Replace image</button>}</div><div className={`upload-zone ${imageUrl ? "has-image" : ""}`}><input key={fileKey} id="post-image" type="file" accept="image/*" onChange={onFileChange} disabled={busy} />{imageUrl ? <img className="new-post-preview" src={imageUrl} alt="Uploaded post preview" /> : <span>{uploading ? "Uploading…" : "Choose an image to upload"}</span>}</div>{(errors.imageUrl || uploadError) && <p className="inline-error">{errors.imageUrl || uploadError}</p>}</section>
    <section className="table-card new-post-fields"><label className="field-label" htmlFor="headline">Headline</label><input id="headline" className="text-input" value={headline} maxLength={HEADLINE_LIMIT} onChange={event => setHeadline(event.target.value)} placeholder="Write a clear, compelling headline" /><div className="field-footer"><span className="field-help">Maximum {HEADLINE_LIMIT} characters.</span><span className="char-count">{headline.length}/{HEADLINE_LIMIT}</span></div>{errors.headline && <p className="inline-error">{errors.headline}</p>}<label className="field-label body-label" htmlFor="body">Body</label><textarea id="body" className="body-input" value={body} maxLength={BODY_LIMIT} onChange={event => setBody(event.target.value)} placeholder="Tell the story in a concise news card." rows={8} /><div className="field-footer"><span className="field-help">Maximum {BODY_LIMIT} characters.</span><span className="char-count">{body.length}/{BODY_LIMIT}</span></div>{errors.body && <p className="inline-error">{errors.body}</p>}</section>
    {errors.submit && <p className="form-message">{errors.submit}</p>}<div className="new-post-actions"><button className="button preview-button" type="submit" disabled={busy}>Preview <span aria-hidden="true">→</span></button><button className="save-draft-button" type="button" onClick={() => void saveDraft("draft")} disabled={busy}>Save as Draft</button></div>
  </form></AdminFrame>;
}

function statusText(status: string, scheduledTime: Date | null) { if (status === "pending_review") return "Pending Review"; if (status === "scheduled") return `Scheduled for ${new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(scheduledTime as Date))}`; if (status === "published") return "Published"; return "Draft"; }

export function PreviewPage() {
  const [, params] = useRoute("/admin/preview/:draftId"); const [location, navigate] = useLocation(); const session = trpc.admin.session.useQuery(); const id = Number(params?.draftId || 0); const post = trpc.admin.post.useQuery({ id }, { enabled: Boolean(session.data && id) });
  const utils = trpc.useUtils(); const submit = trpc.admin.submitPost.useMutation({ onSuccess: () => { void utils.admin.posts.invalidate(); navigate("/admin?message=submitted"); } }); const publish = trpc.admin.publishPost.useMutation({ onSuccess: () => { void utils.admin.posts.invalidate(); navigate("/admin?message=published"); } }); const schedule = trpc.admin.schedulePost.useMutation({ onSuccess: () => { void utils.admin.posts.invalidate(); navigate("/admin?message=scheduled"); } }); const approve = trpc.admin.approvePost.useMutation({ onSuccess: () => { void utils.admin.posts.invalidate(); navigate("/admin?message=approved"); } }); const reject = trpc.admin.rejectPost.useMutation({ onSuccess: () => { void utils.admin.posts.invalidate(); navigate("/admin?message=rejected"); } });
  const [scheduleTime, setScheduleTime] = useState(""); const [rejectionNote, setRejectionNote] = useState(""); const [error, setError] = useState("");
  if (session.isLoading || post.isLoading) return <main className="auth-wrap"><p className="muted">Loading preview…</p></main>;
  if (!session.data || !post.data || !params) return <NotFound />;
  const item = post.data; const isAdmin = session.data.role === "admin"; const isReview = isAdmin && item.status === "pending_review"; const busy = submit.isPending || publish.isPending || schedule.isPending || approve.isPending || reject.isPending;
  function run(action: () => void) { setError(""); try { action(); } catch (err) { setError(err instanceof Error ? err.message : "Action failed"); } }
  function schedulePost(approvePending: boolean) { if (!scheduleTime) { setError("Choose a specific date and time first."); return; } const time = new Date(scheduleTime); if (time <= new Date()) { setError("Scheduled time must be in the future."); return; } if (approvePending) approve.mutate({ id, scheduledTime: time }); else schedule.mutate({ id, scheduledTime: time }); }
  return <AdminFrame role={session.data.role}><div className="preview-topline"><div><p className="eyebrow">Editorial preview</p><h1>Review post</h1></div><span className={`status-badge ${item.status}`}>{statusText(item.status, item.scheduledTime)}</span></div><div className="wysiwyg-card"><img src={item.imageUrl || ""} alt="" className="wysiwyg-image" /><div className="wysiwyg-copy"><p className="eyebrow">Aurikrex Bytes</p><h2>{item.headline}</h2><p>{item.body}</p><span className="watermark">AB</span></div></div><div className="preview-controls"><Link className="outline-button" href={`/admin/new/${id}`}>Edit</Link>{error && <p className="inline-error">{error}</p>}{isReview && <div className="review-note"><label className="field-label" htmlFor="rejection-note">Rejection note <span className="field-help">optional</span></label><textarea id="rejection-note" className="body-input" value={rejectionNote} maxLength={2000} onChange={event => setRejectionNote(event.target.value)} placeholder="Explain what should be revised before resubmission." rows={3} /></div>}{(isAdmin || session.data.role === "editor") && <div className="preview-actions">{isReview ? <><label className="schedule-picker"><span>Schedule for</span><input type="datetime-local" value={scheduleTime} onChange={event => setScheduleTime(event.target.value)} /></label><button className="button preview-action" disabled={busy} onClick={() => run(() => schedulePost(true))}>Approve &amp; Schedule</button><button className="button preview-action" disabled={busy} onClick={() => run(() => approve.mutate({ id }))}>Approve &amp; Publish Now</button><button className="save-draft-button reject-button" disabled={busy} onClick={() => run(() => reject.mutate({ id, rejectionNote: rejectionNote || undefined }))}>Reject</button></> : isAdmin ? <><label className="schedule-picker"><span>Schedule for</span><input type="datetime-local" value={scheduleTime} onChange={event => setScheduleTime(event.target.value)} /></label><button className="button preview-action" disabled={busy} onClick={() => run(() => schedulePost(false))}>Schedule</button><button className="button preview-action" disabled={busy} onClick={() => run(() => publish.mutate({ id }))}>Publish Now</button></> : <button className="button preview-action" disabled={busy} onClick={() => run(() => submit.mutate({ id }))}>Submit for Review</button>}</div>}</div></AdminFrame>;
}
